name: Arch Linux CFS current CI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
      - uses: actions/checkout@v2
      - name: Compile
        run: |
          useradd user -G wheel && echo "user ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown user -R ..
          chown user -R /tmp
          sed -i 's/noccache="false"/noccache="true"/' customization.cfg
          sed -i 's/cpusched=""/cpusched="cfs"/' customization.cfg
          sed -i 's/anbox=""/anbox="true"/' customization.cfg
          sed -i 's/processor_opt=""/processor_opt="generic"/' customization.cfg
          su user -c "yes ''|PKGDEST=/tmp/linux-tkg makepkg --noconfirm -s"

      - name: Archive the artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linux-tkg-build
          path: /tmp/linux-tkg
